config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'
  resources :photos, only: [:new, :index, :create]
  resources :oauth, only: :create do
    collection do
      get "callback"
    end
  end
  resources :tweets, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
class Photo < ApplicationRecord
  include Rails.application.routes.url_helpers
  belongs_to :user

  validates :title, presence: true, length: { maximum: 30 }
  validates :image, presence: true

  has_one_attached :image

  def url
    url_for(image)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_create :create_remember_token

  # 8桁以上 && 大小英数字および記号を含む
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)(?=.*?[\W_])[!-~]{8,}+\z/

  has_many :photos

  validates :user_id, presence: true, uniqueness: true
  validates :password, format: { with: VALID_PASSWORD_REGEX }, on: :create
  validates :password_confirmation, presence: true, on: :create

  has_secure_password

  class << self
    def new_remember_token
      SecureRandom.urlsafe_base64
    end

    def encrypt(token)
      Digest::SHA256.hexdigest(token.to_s)
    end
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :current_user
  before_action :sign_in_required

  def tweet_app_settings
    Rails.application.config_for(:settings)[:tweet_app]
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def create
    uri = URI(tweet_app_settings[:authorization_uri])

    uri.query = {
      response_type: "code",
      client_id: ENV["TWEET_APP_CLIENT_ID"],
      redirect_uri: tweet_app_settings[:redirect_uri]
    }.to_query

    redirect_to uri.to_s, allow_other_host: true
  end

  def callback
    uri = URI.parse(tweet_app_settings[:get_access_token_uri])
    code = params[:code]

    params = {
      grant_type: "authorization_code",
      client_id: ENV["TWEET_APP_CLIENT_ID"],
      client_secret: ENV["TWEET_APP_CLIENT_SECRET"],
      redirect_uri: tweet_app_settings[:redirect_uri],
      code: code,
    }

    response = Net::HTTP.post_form(uri, params)
    session[:access_token] = JSON.parse(response.body)["access_token"]

    redirect_to photos_path
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def new
    @photo = Photo.new
  end

  def index
    @photos = Photo.where(user_id: @current_user.id).order(created_at: :desc)
  end

  def create
    @photo = current_user.photos.build(photo_params)
    if @photo.save
      redirect_to photos_path
    else
      render :new
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :sign_in_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(user_id: session_params[:user_id])

    if user && user.authenticate(session_params[:password])
      sign_in(user)
      redirect_to photos_path
    else
      flash.now[:alert] = alert_messages(user)
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to sign_in_path
  end

  private

  def session_params
    params.require(:session).permit(:user_id, :password)
  end

  def alert_messages(user)
    alert_messages = []
    alert_messages << I18n.t('errors.user.blank.user_id') if session_params[:user_id].blank?
    alert_messages << I18n.t('errors.user.blank.password') if session_params[:password].blank?
    alert_messages << I18n.t('errors.user.record_not_found') if alert_messages.blank? && (user.blank? || !user&.authenticate(session_params[:password]))
    alert_messages
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def create
    photo = Photo.find(params[:photo])
    uri = URI.parse(tweet_app_settings[:post_tweet_uri])
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = uri.scheme === "https"

    params = { text: photo.title, url: photo.url}
    headers = { "Content-Type" => "application/json", "Authorization" => "Bearer #{session[:access_token]}" }
    http.post(uri.path, params.to_json, headers)

    redirect_to photos_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    remember_token = User.encrypt(cookies[:user_remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:user_remember_token] = remember_token
    user.update!(remember_token: User.encrypt(remember_token))
    @current_user = user
  end

  def sign_out
    @current_user = nil
    cookies.delete(:user_remember_token)
    reset_session
  end

  private

  def sign_in_required
    redirect_to sign_in_path if @current_user.blank?
  end
 end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnifaTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_header.html.erb
<%= link_to "ログアウト", sign_out_path %>

app/views/photos/index.html.erb
<%= render 'photos/header' %>

<h1>写真一覧</h1>

<%= button_to "MYTweetAppと連携", oauth_index_path,　method: :post %>
<%= link_to "ファイルをアップロードする", new_photo_path %>

<% if @photos.present? %>
  <div class="photo-list">
    <% @photos.each do |photo| %>
      <div class="photo">
        <div class=title >
          <%= photo.title %>
        </div>
        <% if photo.image.attached? %>
          <%= image_tag photo.image, class:'image' %>
        <% end %>
        <% if session[:access_token].present? %>
          <%= button_to "ツイートする", tweets_path(photo: photo) %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/new.html.erb
<%= render 'photos/header' %>

<%= form_with model: @photo, local: true  do |f| %>
<% if @photo.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <%= f.label :title, "タイトル"%>
  <%= f.text_area :title %><br>
  <%= f.label :image, "画像ファイル"%>
  <%= f.file_field :image %><br>
  <%= f.submit 'アップロード' %>
<% end %>

<%= link_to "キャンセル", photos_path %>